"""
Report Generator

Generate HTML and PDF reports for validation and review.

Implements REQ-QA-04: Report Generation.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Dict, Any, Optional, List
from enum import Enum
from pathlib import Path
from datetime import datetime
import json


class ReportFormat(Enum):
    """Report output format."""
    HTML = "html"
    PDF = "pdf"
    JSON = "json"
    MARKDOWN = "markdown"


# =============================================================================
# HTML TEMPLATES
# =============================================================================

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 20px;
        }}
        .header h1 {{
            margin: 0 0 10px 0;
        }}
        .header .meta {{
            opacity: 0.9;
        }}
        .summary {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
            margin-bottom: 20px;
        }}
        .summary-card {{
            background: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        .summary-card h3 {{
            margin: 0 0 10px 0;
            color: #666;
        }}
        .summary-card .value {{
            font-size: 2em;
            font-weight: bold;
        }}
        .pass {{ color: #22c55e; }}
        .error {{ color: #ef4444; }}
        .warning {{ color: #f59e0b; }}
        .info {{ color: #3b82f6; }}
        .results {{
            background: white;
            border-radius: 10px;
            padding: 20px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        .result-item {{
            padding: 15px;
            border-bottom: 1px solid #eee;
        }}
        .result-item:last-child {{
            border-bottom: none;
        }}
        .result-item .level {{
            display: inline-block;
            padding: 4px 12px;
            border-radius: 20px;
            font-size: 0.85em;
            font-weight: 500;
        }}
        .level-pass {{ background: #dcfce7; color: #166534; }}
        .level-error {{ background: #fee2e2; color: #991b1b; }}
        .level-warning {{ background: #fef3c7; color: #92400e; }}
        .level-info {{ background: #dbeafe; color: #1e40af; }}
        .footer {{
            text-align: center;
            margin-top: 30px;
            color: #666;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{title}</h1>
        <div class="meta">
            Generated: {timestamp}<br>
            Scene: {scene_name}
        </div>
    </div>

    <div class="summary">
        <div class="summary-card">
            <h3>Total Checks</h3>
            <div class="value">{total}</div>
        </div>
        <div class="summary-card">
            <h3>Passed</h3>
            <div class="value pass">{passed}</div>
        </div>
        <div class="summary-card">
            <h3>Errors</h3>
            <div class="value error">{errors}</div>
        </div>
        <div class="summary-card">
            <h3>Warnings</h3>
            <div class="value warning">{warnings}</div>
        </div>
    </div>

    <div class="results">
        <h2>Validation Results</h2>
        {results_html}
    </div>

    <div class="footer">
        Generated by Blender GSD Review System
    </div>
</body>
</html>
"""


# =============================================================================
# REPORT GENERATOR CLASS
# =============================================================================

class ReportGenerator:
    """
    Generate reports from validation and review data.

    Usage:
        generator = ReportGenerator()
        generator.generate_html(validation_report, "report.html")
        generator.generate_pdf(validation_report, "report.pdf")
    """

    def __init__(self):
        """Initialize report generator."""
        self._report_counter = 0

    def generate_html(
        self,
        data: Dict[str, Any],
        output_path: str,
        title: str = "Validation Report",
    ) -> bool:
        """
        Generate HTML report.

        Args:
            data: Report data
            output_path: Output file path
            title: Report title

        Returns:
            Success status
        """
        # Extract data
        summary = data.get("summary", {})
        results = data.get("results", [])

        # Build results HTML
        results_html = ""
        for result in results:
            level = result.get("level", "info")
            category = result.get("category", "general")
            message = result.get("message", "")
            object_name = result.get("object_name", "")
            suggestion = result.get("suggestion", "")

            results_html += f"""
            <div class="result-item">
                <span class="level level-{level}">{level.upper()}</span>
                <span style="color: #666; margin-left: 10px;">{category}</span>
                <p style="margin: 10px 0 5px 0;"><strong>{message}</strong></p>
                {f'<p style="color: #888; margin: 0;">Object: {object_name}</p>' if object_name else ''}
                {f'<p style="color: #666; margin: 5px 0;">Suggestion: {suggestion}</p>' if suggestion else ''}
            </div>
            """

        # Build full HTML
        html = HTML_TEMPLATE.format(
            title=title,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            scene_name=data.get("scene_name", "Unknown"),
            total=summary.get("total", 0),
            passed=summary.get("pass", 0),
            errors=summary.get("error", 0),
            warnings=summary.get("warning", 0),
            results_html=results_html,
        )

        # Write file
        try:
            with open(output_path, "w") as f:
                f.write(html)
            return True
        except IOError:
            return False

    def generate_pdf(
        self,
        data: Dict[str, Any],
        output_path: str,
        title: str = "Validation Report",
    ) -> bool:
        """
        Generate PDF report.

        Args:
            data: Report data
            output_path: Output file path
            title: Report title

        Returns:
            Success status

        Note:
            Requires PDF generation library (e.g., weasyprint, pdfkit)
        """
        # Generate HTML first
        html_path = output_path.replace(".pdf", ".html")
        if not self.generate_html(data, html_path, title):
            return False

        # Placeholder - actual implementation would convert HTML to PDF
        # using a library like weasyprint, pdfkit, or wkhtmltopdf

        return True

    def generate_markdown(
        self,
        data: Dict[str, Any],
        output_path: str,
        title: str = "Validation Report",
    ) -> bool:
        """
        Generate Markdown report.

        Args:
            data: Report data
            output_path: Output file path
            title: Report title

        Returns:
            Success status
        """
        summary = data.get("summary", {})
        results = data.get("results", [])

        md = f"""# {title}

**Scene:** {data.get('scene_name', 'Unknown')}
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Summary

| Metric | Count |
|--------|-------|
| Total | {summary.get('total', 0)} |
| Passed | {summary.get('pass', 0)} |
| Errors | {summary.get('error', 0)} |
| Warnings | {summary.get('warning', 0)} |

## Results

"""
        for result in results:
            level = result.get("level", "info").upper()
            category = result.get("category", "general")
            message = result.get("message", "")
            object_name = result.get("object_name", "")
            suggestion = result.get("suggestion", "")

            level_emoji = {
                "PASS": "✅",
                "ERROR": "❌",
                "WARNING": "⚠️",
                "INFO": "ℹ️",
            }.get(level, "•")

            md += f"### {level_emoji} {level} - {category}\n\n"
            md += f"{message}\n\n"
            if object_name:
                md += f"**Object:** {object_name}\n\n"
            if suggestion:
                md += f"**Suggestion:** {suggestion}\n\n"
            md += "---\n\n"

        try:
            with open(output_path, "w") as f:
                f.write(md)
            return True
        except IOError:
            return False

    def generate_json(
        self,
        data: Dict[str, Any],
        output_path: str,
    ) -> bool:
        """
        Generate JSON report.

        Args:
            data: Report data
            output_path: Output file path

        Returns:
            Success status
        """
        try:
            with open(output_path, "w") as f:
                json.dump(data, f, indent=2)
            return True
        except IOError:
            return False

    def generate(
        self,
        data: Dict[str, Any],
        output_path: str,
        format: str = "html",
        title: str = "Validation Report",
    ) -> bool:
        """
        Generate report in specified format.

        Args:
            data: Report data
            output_path: Output file path
            format: Output format (html, pdf, json, markdown)
            title: Report title

        Returns:
            Success status
        """
        format = format.lower()

        if format == "html":
            return self.generate_html(data, output_path, title)
        elif format == "pdf":
            return self.generate_pdf(data, output_path, title)
        elif format == "json":
            return self.generate_json(data, output_path)
        elif format == "markdown" or format == "md":
            return self.generate_markdown(data, output_path, title)
        else:
            return False


# =============================================================================
# CONVENIENCE FUNCTIONS
# =============================================================================

def generate_report(
    data: Dict[str, Any],
    output_path: str,
    format: str = "html",
    title: str = "Validation Report",
) -> bool:
    """
    Convenience function for report generation.

    Args:
        data: Report data
        output_path: Output file path
        format: Output format
        title: Report title

    Returns:
        Success status
    """
    generator = ReportGenerator()
    return generator.generate(data, output_path, format, title)


# =============================================================================
# EXPORTS
# =============================================================================

__all__ = [
    # Enums
    "ReportFormat",
    # Classes
    "ReportGenerator",
    # Functions
    "generate_report",
]
