"""
Quetzalcoatl - Procedural Feathered Serpent Generator

A procedural creature generation system following the Universal Stage Order:
- Stage 0: Normalize (parameter validation)
- Stage 1: Primary (spine, body, head placement)
- Stage 2: Secondary (eyes, limbs, wings)
- Stage 3: Detail (scales, feathers, teeth, whiskers)
- Stage 4: Output Prep (UVs, rigging, export)
"""

from .types import (
    # Enums
    WingType,
    ScaleShape,
    TailType,
    CrestType,
    ColorPattern,
    # Config dataclasses
    SpineConfig,
    BodyConfig,
    LimbConfig,
    WingConfig,
    ScaleConfig,
    FeatherConfig,
    HeadConfig,
    TeethConfig,
    WhiskerConfig,
    TailConfig,
    ColorConfig,
    AnimationConfig,
    QuetzalcoatlConfig,
)
from .config import ConfigLoader, load_config
from .spine import SpineGenerator, SpineResult, generate_spine
from .body import BodyGenerator, BodyResult, BodyRegion, generate_body
from .head import (
    HeadGenerator,
    HeadResult,
    HeadFeature,
    FeatureSocket,
    generate_head,
)
from .limb import (
    LimbGenerator,
    LimbResult,
    AllLimbsResult,
    LimbSegment,
    LimbSide,
    JointSocket,
    generate_limbs,
)
from .wing import (
    WingGenerator,
    WingResult,
    AllWingsResult,
    WingSegment,
    WingSide,
    WingSocket,
    FeatherData,
    generate_wings,
)
from .scale import (
    ScaleGenerator,
    ScaleLayerResult,
    ScaleRegion,
    ScaleData,
    generate_scales,
)
from .feather import (
    FeatherGenerator,
    FeatherLayerResult,
    FeatherRegion,
    FeatherData,
    generate_feathers,
)
from .detail import (
    ToothType,
    WhiskerType,
    ClawType,
    ToothData,
    WhiskerData,
    ClawData,
    TeethResult,
    WhiskerResult,
    ClawResult,
    DetailResult,
    TeethGenerator,
    WhiskerGenerator,
    ClawGenerator,
    DetailGenerator,
    generate_teeth,
    generate_whiskers,
    generate_claws,
    generate_details,
)
from .color import (
    ColorPattern,
    ColorRegion,
    ColorDefinition,
    ColorRegionConfig,
    IridescenceConfig,
    ColorSystemConfig,
    VertexColorResult,
    ColorSystem,
    generate_colors,
    get_color_preset,
    create_config_from_preset,
    COLOR_PRESETS,
)
from .shader import (
    MaterialType,
    ShaderQuality,
    BaseMaterialProperties,
    SubsurfaceScattering,
    IridescenceShader,
    FeatherShaderConfig,
    ScaleShaderConfig,
    EyeShaderConfig,
    MaterialLayer,
    ShaderConfig,
    ShaderNodeData,
    ShaderResult,
    ShaderGenerator,
    generate_shaders,
    get_shader_preset,
    create_generator_from_preset,
    SHADER_PRESETS,
)
from .animation import (
    BoneType,
    RigType,
    BoneDefinition,
    WeightPaintData,
    IKConstraint,
    RigConfig,
    RigResult,
    RigGenerator,
    generate_rig,
    get_rig_preset,
    create_config_from_preset as create_rig_config_from_preset,
    RIG_PRESETS,
)
from .export import (
    ExportFormat,
    PresetCategory,
    CreaturePreset,
    ExportConfig,
    ExportResult,
    ExportManager,
    CREATURE_PRESETS,
    get_preset,
    list_presets,
    get_presets_by_category,
    export_creature,
    create_custom_preset,
)

__all__ = [
    # Enums
    "WingType",
    "ScaleShape",
    "TailType",
    "CrestType",
    "ColorPattern",
    "BodyRegion",
    "HeadFeature",
    "LimbSegment",
    "LimbSide",
    "WingSegment",
    "WingSide",
    "ScaleRegion",
    "FeatherRegion",
    "ToothType",
    "WhiskerType",
    "ClawType",
    "ColorPattern",
    "ColorRegion",
    # Configs
    "SpineConfig",
    "BodyConfig",
    "LimbConfig",
    "WingConfig",
    "ScaleConfig",
    "FeatherConfig",
    "HeadConfig",
    "TeethConfig",
    "WhiskerConfig",
    "TailConfig",
    "ColorConfig",
    "AnimationConfig",
    "QuetzalcoatlConfig",
    # Loader
    "ConfigLoader",
    "load_config",
    # Spine
    "SpineGenerator",
    "SpineResult",
    "generate_spine",
    # Body
    "BodyGenerator",
    "BodyResult",
    "generate_body",
    # Head
    "HeadGenerator",
    "HeadResult",
    "FeatureSocket",
    "generate_head",
    # Limb
    "LimbGenerator",
    "LimbResult",
    "AllLimbsResult",
    "JointSocket",
    "generate_limbs",
    # Wing
    "WingGenerator",
    "WingResult",
    "AllWingsResult",
    "WingSocket",
    "FeatherData",
    "generate_wings",
    # Scale
    "ScaleGenerator",
    "ScaleLayerResult",
    "ScaleData",
    "generate_scales",
    # Feather
    "FeatherGenerator",
    "FeatherLayerResult",
    "FeatherData",
    "generate_feathers",
    # Detail
    "ToothData",
    "WhiskerData",
    "ClawData",
    "TeethResult",
    "WhiskerResult",
    "ClawResult",
    "DetailResult",
    "TeethGenerator",
    "WhiskerGenerator",
    "ClawGenerator",
    "DetailGenerator",
    "generate_teeth",
    "generate_whiskers",
    "generate_claws",
    "generate_details",
    # Color
    "ColorDefinition",
    "ColorRegionConfig",
    "IridescenceConfig",
    "ColorSystemConfig",
    "VertexColorResult",
    "ColorSystem",
    "generate_colors",
    "get_color_preset",
    "create_config_from_preset",
    "COLOR_PRESETS",
    # Shader
    "MaterialType",
    "ShaderQuality",
    "BaseMaterialProperties",
    "SubsurfaceScattering",
    "IridescenceShader",
    "FeatherShaderConfig",
    "ScaleShaderConfig",
    "EyeShaderConfig",
    "MaterialLayer",
    "ShaderConfig",
    "ShaderNodeData",
    "ShaderResult",
    "ShaderGenerator",
    "generate_shaders",
    "get_shader_preset",
    "create_generator_from_preset",
    "SHADER_PRESETS",
    # Animation
    "BoneType",
    "RigType",
    "BoneDefinition",
    "WeightPaintData",
    "IKConstraint",
    "RigConfig",
    "RigResult",
    "RigGenerator",
    "generate_rig",
    "get_rig_preset",
    "create_rig_config_from_preset",
    "RIG_PRESETS",
    # Export
    "ExportFormat",
    "PresetCategory",
    "CreaturePreset",
    "ExportConfig",
    "ExportResult",
    "ExportManager",
    "CREATURE_PRESETS",
    "get_preset",
    "list_presets",
    "get_presets_by_category",
    "export_creature",
    "create_custom_preset",
]

__version__ = "1.0.0"
